# Generated by Django 3.2.25 on 2024-10-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('IdU', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo', models.EmailField(max_length=255)),
                ('Ciudad', models.CharField(max_length=100)),
                ('FechaIngreso', models.DateField()),
            ],
        ),
    ]
